# TCPShieldDynamicIP config

# TCPShield data - Find out how to get this at https://github.com/moom0o/TCPShieldDynamicIP
Token: "MTUxxxxxxxxxxxxxxxxxxxxxx"
ID: 150000
Domain: "*.domain.com"

#Enable if using a proxy.
Bungeecord: false
BungeePort: 25565
